[package]
name = "first_cargo"
version = "0.1.0"
authors = ["Piradeepan Nagarajan <piradeepann@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dns-lookup = "1.0.4"
crossbeam = "0.8.0"